//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public short TransactionType { get; set; }
        public long Amount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Description { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Transaction Transaction1 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
    }
}
